apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "common.fullname" . }}-secret
data:
  {{- range $key, $value := .Values.secrets }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
